version: '3'
services:
  gebug-itunes-artwork-proxy-api-debug:
    build:
      context: ..
      dockerfile: ./debug/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../:/src:ro
    ports:
      - 5678:80
      - 2345:2345
    environment:
      - LOG_LEVEL=DEBUG
