// Package app provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package app

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi"
)

// Album defines model for Album.
type Album struct {
	ArtistName string `json:"artist_name"`
	ImageUrl   string `json:"image_url"`
	Title      string `json:"title"`
}

// AlbumList defines model for AlbumList.
type AlbumList struct {
	Data []Album `json:"data"`
}

// GetRestV1AlbumSearchParams defines parameters for GetRestV1AlbumSearch.
type GetRestV1AlbumSearchParams struct {

	// return only artwork by artist
	Artist *string `json:"artist,omitempty"`

	// search for albums that match title
	Title string `json:"title"`

	// the size in px of the width and height
	Size *int `json:"size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns all artwork given album.
	// (GET /rest/v1/album/search)
	GetRestV1AlbumSearch(w http.ResponseWriter, r *http.Request, params GetRestV1AlbumSearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetRestV1AlbumSearch operation middleware
func (siw *ServerInterfaceWrapper) GetRestV1AlbumSearch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRestV1AlbumSearchParams

	// ------------- Optional query parameter "artist" -------------
	if paramValue := r.URL.Query().Get("artist"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "artist", r.URL.Query(), &params.Artist)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter artist: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "title" -------------
	if paramValue := r.URL.Query().Get("title"); paramValue != "" {

	} else {
		http.Error(w, "Query argument title is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "title", r.URL.Query(), &params.Title)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter title: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------
	if paramValue := r.URL.Query().Get("size"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "size", r.URL.Query(), &params.Size)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter size: %s", err), http.StatusBadRequest)
		return
	}

	siw.Handler.GetRestV1AlbumSearch(w, r.WithContext(ctx), params)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerFromMux(si, chi.NewRouter())
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	r.Group(func(r chi.Router) {
		r.Get("/rest/v1/album/search", wrapper.GetRestV1AlbumSearch)
	})

	return r
}

